FROM rustlang/rust:nightly-slim as builder
RUN apt update && apt-get install default-libmysqlclient-dev -y
RUN rustup target add --toolchain nightly x86_64-unknown-linux-musl

WORKDIR /subject-ms
COPY Cargo.* ./
COPY src src
RUN cargo build --release

FROM debian:stable-slim
RUN apt-get update && apt-get install default-libmysqlclient-dev -y

COPY --from=builder /subject-ms/target/release/subject-ms .
COPY Rocket.toml .
CMD ./subject-ms
